#Locators.py


class Employee_Locators:
    username_locator = 'username'
    password_locator1 = 'password'
    submitBox_locator = '//*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button'
    searchbox_locator = '//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/div/div/input'
    Adminbox_locator = '//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a'
    Sidepane_locator ='//*[@id="app"]/div[1]/div[1]/aside/nav'
    Sidepane1_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[2]/div[1]/button'
    Usermanagement_locator='//*[@id="app"]/div[1]/div[1]/header/div[2]/nav/ul/li[1]/span'
    Userselecting_locator='//*[@id="app"]/div[1]/div[1]/header/div[2]/nav/ul/li[1]/ul/li'
    UsernameBox_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[1]/div/div[2]/input'
    userrole = "(//*[@class='oxd-select-text-input'])[1]"
    dropdown1_locator = "(//*[@role='listbox'])"
    value1 = "(//*[@class='oxd-select-text-input'])[2]"
    value2 = "(//*[@class='oxd-select-text-input'])[2]"
    dropdown2_locator = '(//*[@role="listbox"])'
    Pimmodulebutton_locator= '//*[@id="app"]/div[1]/div[1]/aside/nav/div[2]/ul/li[2]/a'
    AddEmployee_locator='Add Employee'
    Firstname_locator = 'firstName'
    Middlename_locator = 'middleName'
    Lastname_locator = 'lastName'
    Radiobutton_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[2]/div/label/span'
    User_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[3]/div/div[1]/div/div[2]/input'
    Password_locator2 = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[1]/div/div[2]/input'
    Confirmpassword_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[1]/div[2]/div[4]/div/div[2]/div/div[2]/input'
    saveBox_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/form/div[2]/button[2]'
    click_button_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/div[9]/div/button[2]/i'
    Nickename_locator ='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div[2]/div/div/div[2]/input'
    GenderBox_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[2]/div/div[2]/div[2]/div[2]/div/label'   
    Dateofbirth_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div[2]/div[1]/div/div[2]/div/div/input'
    Save1_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button'
    Save2_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/form/div[2]/button'
    Employeelist_locator='Employee List'
    Employeename_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[1]/div/div[2]/div/div/input'
    Employeeid_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[1]/div/div[2]/div/div[2]/input'
    otherid_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[1]/div[2]/div/div[2]/input'
    Drivinglicensenumber_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[1]/div/div[2]/input'
    LicenseExpiryDate_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[2]/div[2]/div/div[2]/div/div/input'
    SSNNumber_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[3]/div[1]/div/div[2]/input'
    SINNumber_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div[3]/div[2]/div/div[2]/input'
    MilitaryService_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div/div[1]/div/div[2]/input'
    Nationality_locator='//label[text()="Nationality"]/following::div[1]'
    Nationality_selector = "//div[@role='option']/span[text()='Indian']"
    marital_status='//label[text()="Marital Status"]/following::div[1]'
    maritalstatus_selector="//div[@role='option']/span[text()='Single']"
    bloodgroup_locator = '//label[text()="Blood Type"]/following::div[1]'
    bloodgroup_selector = "//div[@role='option']/span[text()='AB+']"
    Searchbutton_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div[1]/div[2]/form/div[2]/button[2]'
    Contactdetail_locator='Contact Details'
    street1_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    street2_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input'
    city_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[3]/div/div[2]/input'
    state_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[4]/div/div[2]/input'
    zipcode_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/input'
    country_locator = '//label[text()="Country"]/following::div[1]'
    country_selector = "//div[@role='option']/span[text()='India']"
    home_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/input'
    moblie_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input'
    work_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[3]/div/div[2]/input'
    work_mail_locator ='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[1]/div/div[2]/input'
    other_mailid_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[2]/div/div[2]/input'
    save_button1_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/button'
    emergencyContants_locator='Emergency Contacts'
    emergencyaddbutton_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button'
    name_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    relationship_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input'
    homenumber_locator =   '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[1]/div/div[2]/input'
    mobilenumber_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[2]/div/div[2]/input'
    worknumber_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[3]/div/div[2]/input'
    save_button2_locator= '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button[2]'
    dependent_locator= 'Dependents'
    dependentsadd_locator = "(//*[@type='button'])[2]"
    dependentsname_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    relationshipbutton_locator = '//label[text()="Relationship"]/following::div[1]'
    relationshipselecting_locator = '//div[@role="option"]/span[text()="Child"]'
    drop1_down_locator = "//*[@role='listbox']"
    relationdateob_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div/div/div[2]/div/div/input'
    save_button3_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button[2]'
    jobbutton_locator = 'Job'
    joined_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/div/div/input'
    job_title_locator = "//label[normalize-space()='Job Title']/following::div[3]"
    JobTitle_selector = "//div[@role='option']/span[text()='Software Engineer']"
    job_category_locator = '//label[text()="Job Category"]/following::div[1]'
    jobcategory_selector = '//div[@role="option"]/span[text()="Professionals"]'
    subunit_locator = "//label[text()='Sub Unit']/following::div[1]"
    subunit_selector = "//div[@role='option']/span[text()='Quality Assurance']"
    location_locator = "//label[text()='Location']/following::div[1]"
    location_selector = '//div[@role="option"]/span[text()="Canadian Regional HQ"]'
    employeestatus_locator = '//label[text()="Employment Status"]/following::div[1]'
    employmentstatus_selector = '//div[@role="option"]/span[text()="Full-Time Permanent"]'
    EmploymentContractDetailsbutton_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/label/span'
    ContractStartDate_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[1]/div/div[2]/div/div/input'
    ContractEndDate_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/div[2]/div/div[2]/div/div/input'
    save_button5_locator = '(//*[@type="submit"])'
    terminatebutton_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/button'
    terminatedate_locator = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[1]/div/div[2]/div/div/input'
    Terminatereason_locator = '//label[text()="Termination Reason"]/following::div[3]'
    Terminatereasonselector_locator = '//div[@role="option"]/span[text()="Physically Disabled/Compensated"]'
    note = '//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[3]/div/div[2]/textarea'
    save_button6_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[3]/div/div/div/form/div[4]/button[2]'
    activation_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/button'
    salarybutton_locator='Salary'
    salary_add='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/div/button'
    salarycomponent_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[1]/div/div[2]/input'
    Paygrade_locator = '//label[text()="Pay Grade"]/following::div[1]/div'
    paygrade_selector = '//div[@role="option"]/span[text()="Grade 3"]'
    payfrequency_locator = "//label[text()='Pay Frequency']/following::div[1]/div"
    payfrequency_selector = '//div[@role="option"]/span[text()="Monthly"]'
    currency_locator = "//label[text()='Currency']/following::div[1]"
    currency_selector = '//div[@role="option"]/span[text()="United States Dollar"]'
    amount1_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[5]/div/div[2]/input'
    DirectDepositDetailsbuttton_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/div/label/span'
    Accountnumber_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div[1]/div[1]/div/div[2]/input'
    accounttype_locator = '//label[text()="Account Type"]/following::div[1]'
    accounttype_selector = '//div[@role="option"]/span[text() = "Savings"]'
    routingnumber_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div[2]/div[1]/div/div[2]/input'
    amount2_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[4]/div[2]/div[2]/div/div[2]/input'
    save_button7_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[5]/button[2]'
    TaxExemptionsbutton_locator='Tax Exemptions'
    FederalIncomeTaxstatus_locator = '//h6[text()="Federal Income Tax"]/following::div[7]'
    FederalIncomeTaxstatus_selector = '//div[@role="option"]/span[text()="Married"]'
    FederalIncomeTaxExemptions_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[1]/div/div[2]/div/div[2]/input'
    StateIncomeTaxstate_locator='//label[text()="State"]/following::div[1]'
    StateIncomeTaxstate_selector='//div[@role="option"]/span[text()="Indiana"]'
    StateIncomeTaxstatus_locator='//h6[text()="State Income Tax"]/following::div[14]'
    StateIncomeTaxstatus_selector='//div[@role="option"]/span[text()="Married"]'
    StateIncomeTaxExemptions_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[2]/div/div[3]/div/div[2]/input'
    UnemploymentState_locator = '//label[text()="Unemployment State"]/following::div[1]'
    UnemploymentState_selector = '//div[@role="option"]/span[text()="Indiana"]'
    Workstate_locator = '//label[text()="Work State"]/following::div[3]'
    workstate_selector= '//div[@role="option"]/span[text()="Indiana"]'
    Save_button8_locator='//*[@id="app"]/div[1]/div[2]/div[2]/div/div/div/div[2]/div[1]/form/div[3]/button'